// <auto-generated />
namespace ManageProjectStudent_ViewModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v5));
        
        string IMigrationMetadata.Id
        {
            get { return "202008061033078_v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
